language: groovy

jdk:
  - oraclejdk7
  - oraclejdk8

before_install:
 - chmod +x gradlew

script:
 - ./gradlew clean check -DintegTest.single=*IntegSpec

after_success:
 - ./gradlew jacocoTestReport coveralls
