--SQL*PLUS Script to setup all the schemas required for the integTests

--Run as system

CREATE USER utp IDENTIFIED BY utp DEFAULT TABLESPACE
  users TEMPORARY TABLESPACE temp;

GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE,
CREATE SEQUENCE, CREATE VIEW, CREATE PUBLIC SYNONYM,
DROP PUBLIC SYNONYM TO utp;

ALTER USER utp QUOTA UNLIMITED ON users;

CREATE USER testing IDENTIFIED BY testing DEFAULT TABLESPACE
  users TEMPORARY TABLESPACE temp;

GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE,
CREATE SEQUENCE, CREATE VIEW, CREATE PUBLIC SYNONYM,
DROP PUBLIC SYNONYM TO testing;

ALTER USER testing QUOTA UNLIMITED ON users;

CREATE USER schemaOne IDENTIFIED BY schemaOne DEFAULT TABLESPACE
  users TEMPORARY TABLESPACE temp;

GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE,
CREATE SEQUENCE, CREATE VIEW, CREATE PUBLIC SYNONYM,
DROP PUBLIC SYNONYM TO schemaOne;

ALTER USER schemaOne QUOTA UNLIMITED ON users;

CREATE USER schemaTwo IDENTIFIED BY schemaTwo DEFAULT TABLESPACE
  users TEMPORARY TABLESPACE temp;

GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE,
CREATE SEQUENCE, CREATE VIEW, CREATE PUBLIC SYNONYM,
DROP PUBLIC SYNONYM TO schemaTwo;

ALTER USER schemaTwo QUOTA UNLIMITED ON users;

CONN testing/testing@test

@../src/main/plsql/betwnstr.sf
@../src/main/plsql/simple_example.pks
@../src/main/plsql/simple_example.pkb


CONN schemaOne/schemaOne@test

@../src/main/plsql/betwnstr.sf


CONN schemaTwo/schemaTwo@test

@../src/main/plsql/simple_example.pks
@../src/main/plsql/simple_example.pkb
